// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPmLdbVcXOjvIBkMtWsRJbWnppWOnuJw',
    appId: '1:503789742343:web:6e321105df774bcb4cfda2',
    messagingSenderId: '503789742343',
    projectId: 'personal-bio-app-14b36',
    authDomain: 'personal-bio-app-14b36.firebaseapp.com',
    databaseURL: 'https://personal-bio-app-14b36-default-rtdb.firebaseio.com',
    storageBucket: 'personal-bio-app-14b36.firebasestorage.app',
    measurementId: 'G-SHL2EVRVGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlthe-yhTkYQx3Z4w5uu2XgUnc88zTxhM',
    appId: '1:503789742343:android:8484c9009f38f59b4cfda2',
    messagingSenderId: '503789742343',
    projectId: 'personal-bio-app-14b36',
    databaseURL: 'https://personal-bio-app-14b36-default-rtdb.firebaseio.com',
    storageBucket: 'personal-bio-app-14b36.firebasestorage.app',
  );
}
