// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLKbatzrhfNaVVqJhjtO5095pK3QUCwYY',
    appId: '1:30313849035:web:d3e7a84ce518b0d9d4bb4e',
    messagingSenderId: '30313849035',
    projectId: 'student-financial-assistant',
    authDomain: 'student-financial-assistant.firebaseapp.com',
    storageBucket: 'student-financial-assistant.firebasestorage.app',
    measurementId: 'G-R7XP43N8BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPoLJmNYC2kY7KW7lQ_2mJWz2bX5MMtY',
    appId: '1:30313849035:android:b4f7ddb20abcd003d4bb4e',
    messagingSenderId: '30313849035',
    projectId: 'student-financial-assistant',
    storageBucket: 'student-financial-assistant.firebasestorage.app',
  );
}
